import type { Metadata } from "next";

import { Inter } from "next/font/google";

import "@radix-ui/themes/styles.css";
import "./theme-config.css";
import "./globals.css";

import AuthProvider from "./auth/Provider";

import { Container, Theme } from "@radix-ui/themes";

import { Navbar } from "./components";
import QueryClientProvider from "./components/QueryClientProvider";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata: Metadata = {
  title: "Task Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <body className={inter.variable}>
        <QueryClientProvider>
          <AuthProvider>
            <Theme appearance="light" accentColor="violet">
              <Navbar />
              <main className="p-5">
                <Container>{children}</Container>
              </main>
              {/* <ThemePanel /> */}
            </Theme>
          </AuthProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
